### PR TITLE
Fixes retrieval of `ModuleComponentIdentifier`

### PR DESCRIPTION
**Pull request by jvican**
For some reason, the Bloop plugin wouldn't work at all in a private repository using a proprietary version of Gradle. I believe this is because the presence of a certain plugin that was interfering and changing the artifacts available after resolution to be something else than `ModuleComponentArtifactIdentifier`, so the Scala plugin would never collect the Scala library. But, the result was that the Bloop plugin wouldn't generate Bloop files and it would fail altogether.

The following change, which is untested because I couldn't reproduce, has a fix that uses a more general interface `ModuleComponentIdentifier` and pattern matches on `getComponentIdentifier` instead of the regular artifact identifiers. This seems to be the most correct and general way of writing the previous logic.

### CODE REVIEW

**Comment by Arthurm1** [comment]
If it passes the tests then LGTM.  I'm never sure of the correct way of doing anything with the Gradle API :shrug:

**Review by adpi2 — COMMENTED** [review]
Looks good but it needs formatting

**Comment by jvican** [comment]
@Arthurm1 Don't worry about it, it's hard!

@adpi2 Updated!

**Comment by jvican** [comment]
@adpi2 Could you also please cut a release after merging?

**Comment by adpi2** [comment]
Here it is https://github.com/scalacenter/gradle-bloop/releases/tag/v1.6.2

**Pull request merged**
