### PR TITLE
fix: delete stale config files

### PR DESCRIPTION
**Pull request by kasiaMarek**
connected to: https://github.com/scalameta/metals/issues/6253

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
Looks good! @Arthurm1 do you want to confirm?

**Review by tgodzik — CHANGES_REQUESTED** [review]
Och, actually the CI failed, could you take a look?

**Comment by Arthurm1** [comment]
You can't really clean up the `.bloop` dir this way.

The plugin is run per project/subproject so if you are importing a Gradle build that has multiple projects (e.g. `Foo` and `Bar`) then `bloopInstall` will import `Foo` and then when it tries to import `Bar` it will now delete the `.bloop/Foo.json` file - hence the CI failures.

It might be better to do this in Metals as off the top of my head I suspect the best way is to alter the `init-script.gradle` script.

You could add something like
```
// I haven't tested this but...
tasks.register('bloopClean', Delete) {
    delete '.bloop'
}
```
and then change the `bloopInstall` exec to be something like...
`./gradlew --init-script /tmp/metals5311744264606695985/init-script.gradle bloopClean bloopInstall`

Another option would be to change Metals to always remove `.bloop` before importing regardless of whether the import is Gradle, SBT, Maven as I suspect this might apply to other build tool imports.

If you want this to be a Gradle only thing then I can look at this next week.

**Comment by kasiaMarek** [comment]
> The plugin is run per project/subproject
Oh, I see. I'm closing this then.

> Gradle, SBT, Maven as I suspect this might apply to other build tool imports
Don't know about `Maven` but `SBT` plugin deletes old config files.

> It might be better to do this in Metals as off the top of my head I suspect the best way is to alter the init-script.gradle script.

Deleting the whole `.bloop` will delete some bloop caches, not sure if that's an issue (e.g. stale semanticdbs might still be useful), @tgodzik?

**Comment by kasiaMarek** [comment]
Fixing this in Metals: https://github.com/scalameta/metals/pull/6305.

**Pull request closed without merging**
